// <auto-generated />
namespace WebAPIPhase_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class roleadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roleadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201602212307279_roleadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
